import sys
import time
from dataclasses import dataclass
from typing import List
import random

MEASUREMENT_FILE = "../data/measurements.csv"

@dataclass
class WeatherStation:
    id: str
    mean_temperature: float
    
    @property
    def measurement(self) -> float:
        return self.mean_temperature + (random.random() * 20) - 10
    
    def __str__(self) -> str:
        return f"{self.id};{self.measurement:.1f}"


stations = [
    WeatherStation("Abha", 18.0),
    WeatherStation("Abidjan", 26.0),
    WeatherStation("Abéché", 29.4),
    WeatherStation("Accra", 26.4),
    WeatherStation("Addis Ababa", 16.0),
    WeatherStation("Adelaide", 17.3),
    WeatherStation("Aden", 29.1),
    WeatherStation("Ahvaz", 25.4),
    WeatherStation("Albuquerque", 14.0),
    WeatherStation("Alexandra", 11.0),
    WeatherStation("Alexandria", 20.0),
    WeatherStation("Algiers", 18.2),
    WeatherStation("Alice Springs", 21.0),
    WeatherStation("Almaty", 10.0),
    WeatherStation("Amsterdam", 10.2),
    WeatherStation("Anadyr", -6.9),
    WeatherStation("Anchorage", 2.8),
    WeatherStation("Andorra la Vella", 9.8),
    WeatherStation("Ankara", 12.0),
    WeatherStation("Antananarivo", 17.9),
    WeatherStation("Antsiranana", 25.2),
    WeatherStation("Arkhangelsk", 1.3),
    WeatherStation("Ashgabat", 17.1),
    WeatherStation("Asmara", 15.6),
    WeatherStation("Assab", 30.5),
    WeatherStation("Astana", 3.5),
    WeatherStation("Athens", 19.2),
    WeatherStation("Atlanta", 17.0),
    WeatherStation("Auckland", 15.2),
    WeatherStation("Austin", 20.7),
    WeatherStation("Baghdad", 22.77),
    WeatherStation("Baguio", 19.5),
    WeatherStation("Baku", 15.1),
    WeatherStation("Baltimore", 13.1),
    WeatherStation("Bamako", 27.8),
    WeatherStation("Bangkok", 28.6),
    WeatherStation("Bangui", 26.0),
    WeatherStation("Banjul", 26.0),
    WeatherStation("Barcelona", 18.2),
    WeatherStation("Bata", 25.1),
    WeatherStation("Batumi", 14.0),
    WeatherStation("Beijing", 12.9),
    WeatherStation("Beirut", 20.9),
    WeatherStation("Belgrade", 12.5),
    WeatherStation("Belize City", 26.7),
    WeatherStation("Benghazi", 19.9),
    WeatherStation("Bergen", 7.7),
    WeatherStation("Berlin", 10.3),
    WeatherStation("Bilbao", 14.7),
    WeatherStation("Birao", 26.5),
    WeatherStation("Bishkek", 11.3),
    WeatherStation("Bissau", 27.0),
    WeatherStation("Blantyre", 22.2),
    WeatherStation("Bloemfontein", 15.6),
    WeatherStation("Boise", 11.4),
    WeatherStation("Bordeaux", 14.2),
    WeatherStation("Bosaso", 30.0),
    WeatherStation("Boston", 10.9),
    WeatherStation("Bouaké", 26.0),
    WeatherStation("Bratislava", 10.5),
    WeatherStation("Brazzaville", 25.0),
    WeatherStation("Bridgetown", 27.0),
    WeatherStation("Brisbane", 21.4),
    WeatherStation("Brussels", 10.5),
    WeatherStation("Bucharest", 10.8),
    WeatherStation("Budapest", 11.3),
    WeatherStation("Bujumbura", 23.8),
    WeatherStation("Bulawayo", 18.9),
    WeatherStation("Burnie", 13.1),
    WeatherStation("Busan", 15.0),
    WeatherStation("Cabo San Lucas", 23.9),
    WeatherStation("Cairns", 25.0),
    WeatherStation("Cairo", 21.4),
    WeatherStation("Calgary", 4.4),
    WeatherStation("Canberra", 13.1),
    WeatherStation("Cape Town", 16.2),
    WeatherStation("Changsha", 17.4),
    WeatherStation("Charlotte", 16.1),
    WeatherStation("Chiang Mai", 25.8),
    WeatherStation("Chicago", 9.8),
    WeatherStation("Chihuahua", 18.6),
    WeatherStation("Chișinău", 10.2),
    WeatherStation("Chittagong", 25.9),
    WeatherStation("Chongqing", 18.6),
    WeatherStation("Christchurch", 12.2),
    WeatherStation("City of San Marino", 11.8),
    WeatherStation("Colombo", 27.4),
    WeatherStation("Columbus", 11.7),
    WeatherStation("Conakry", 26.4),
    WeatherStation("Copenhagen", 9.1),
    WeatherStation("Cotonou", 27.2),
    WeatherStation("Cracow", 9.3),
    WeatherStation("Da Lat", 17.9),
    WeatherStation("Da Nang", 25.8),
    WeatherStation("Dakar", 24.0),
    WeatherStation("Dallas", 19.0),
    WeatherStation("Damascus", 17.0),
    WeatherStation("Dampier", 26.4),
    WeatherStation("Dar es Salaam", 25.8),
    WeatherStation("Darwin", 27.6),
    WeatherStation("Denpasar", 23.7),
    WeatherStation("Denver", 10.4),
    WeatherStation("Detroit", 10.0),
    WeatherStation("Dhaka", 25.9),
    WeatherStation("Dikson", -11.1),
    WeatherStation("Dili", 26.6),
    WeatherStation("Djibouti", 29.9),
    WeatherStation("Dodoma", 22.7),
    WeatherStation("Dolisie", 24.0),
    WeatherStation("Douala", 26.7),
    WeatherStation("Dubai", 26.9),
    WeatherStation("Dublin", 9.8),
    WeatherStation("Dunedin", 11.1),
    WeatherStation("Durban", 20.6),
    WeatherStation("Dushanbe", 14.7),
    WeatherStation("Edinburgh", 9.3),
    WeatherStation("Edmonton", 4.2),
    WeatherStation("El Paso", 18.1),
    WeatherStation("Entebbe", 21.0),
    WeatherStation("Erbil", 19.5),
    WeatherStation("Erzurum", 5.1),
    WeatherStation("Fairbanks", -2.3),
    WeatherStation("Fianarantsoa", 17.9),
    WeatherStation("Flores,  Petén", 26.4),
    WeatherStation("Frankfurt", 10.6),
    WeatherStation("Fresno", 17.9),
    WeatherStation("Fukuoka", 17.0),
    WeatherStation("Gabès", 19.5),
    WeatherStation("Gaborone", 21.0),
    WeatherStation("Gagnoa", 26.0),
    WeatherStation("Gangtok", 15.2),
    WeatherStation("Garissa", 29.3),
    WeatherStation("Garoua", 28.3),
    WeatherStation("George Town", 27.9),
    WeatherStation("Ghanzi", 21.4),
    WeatherStation("Gjoa Haven", -14.4),
    WeatherStation("Guadalajara", 20.9),
    WeatherStation("Guangzhou", 22.4),
    WeatherStation("Guatemala City", 20.4),
    WeatherStation("Halifax", 7.5),
    WeatherStation("Hamburg", 9.7),
    WeatherStation("Hamilton", 13.8),
    WeatherStation("Hanga Roa", 20.5),
    WeatherStation("Hanoi", 23.6),
    WeatherStation("Harare", 18.4),
    WeatherStation("Harbin", 5.0),
    WeatherStation("Hargeisa", 21.7),
    WeatherStation("Hat Yai", 27.0),
    WeatherStation("Havana", 25.2),
    WeatherStation("Helsinki", 5.9),
    WeatherStation("Heraklion", 18.9),
    WeatherStation("Hiroshima", 16.3),
    WeatherStation("Ho Chi Minh City", 27.4),
    WeatherStation("Hobart", 12.7),
    WeatherStation("Hong Kong", 23.3),
    WeatherStation("Honiara", 26.5),
    WeatherStation("Honolulu", 25.4),
    WeatherStation("Houston", 20.8),
    WeatherStation("Ifrane", 11.4),
    WeatherStation("Indianapolis", 11.8),
    WeatherStation("Iqaluit", -9.3),
    WeatherStation("Irkutsk", 1.0),
    WeatherStation("Istanbul", 13.9),
    WeatherStation("İzmir", 17.9),
    WeatherStation("Jacksonville", 20.3),
    WeatherStation("Jakarta", 26.7),
    WeatherStation("Jayapura", 27.0),
    WeatherStation("Jerusalem", 18.3),
    WeatherStation("Johannesburg", 15.5),
    WeatherStation("Jos", 22.8),
    WeatherStation("Juba", 27.8),
    WeatherStation("Kabul", 12.1),
    WeatherStation("Kampala", 20.0),
    WeatherStation("Kandi", 27.7),
    WeatherStation("Kankan", 26.5),
    WeatherStation("Kano", 26.4),
    WeatherStation("Kansas City", 12.5),
    WeatherStation("Karachi", 26.0),
    WeatherStation("Karonga", 24.4),
    WeatherStation("Kathmandu", 18.3),
    WeatherStation("Khartoum", 29.9),
    WeatherStation("Kingston", 27.4),
    WeatherStation("Kinshasa", 25.3),
    WeatherStation("Kolkata", 26.7),
    WeatherStation("Kuala Lumpur", 27.3),
    WeatherStation("Kumasi", 26.0),
    WeatherStation("Kunming", 15.7),
    WeatherStation("Kuopio", 3.4),
    WeatherStation("Kuwait", 25.0),
    WeatherStation("Kyiv", 8.4),
    WeatherStation("Kyoto", 15.7),
    WeatherStation("La Ceiba", 26.2),
    WeatherStation("La Paz", 17.8),
    WeatherStation("La Romana", 25.9),
    WeatherStation("La Serena", 14.4),
    WeatherStation("Labasa", 26.1),
    WeatherStation("Labuan", 27.3),
    WeatherStation("Lac-Mégantic", 6.4),
    WeatherStation("Lagos", 26.8),
    WeatherStation("Lahore", 24.9),
    WeatherStation("Lake Havasu City", 23.7),
    WeatherStation("Lamezia Terme", 16.0),
    WeatherStation("Lampedusa", 18.6),
    WeatherStation("Lanzhou", 10.4),
    WeatherStation("Lanzarote", 20.6),
    WeatherStation("Laredo", 23.3),
    WeatherStation("Larisa", 15.5),
    WeatherStation("Las Palmas", 21.6),
    WeatherStation("Las Vegas", 20.3),
    WeatherStation("Launceston", 13.1),
    WeatherStation("Lausanne", 10.6),
    WeatherStation("Laverton", 22.8),
    WeatherStation("Lawrence", 12.7),
    WeatherStation("Le Mans", 11.9),
    WeatherStation("Leeds", 9.4),
    WeatherStation("Leh", 7.6),
    WeatherStation("Léopoldville", 25.3),
    WeatherStation("Lerwick", 6.9),
    WeatherStation("Les Abymes", 26.1),
    WeatherStation("Leskovac", 11.0),
    WeatherStation("Leuven", 10.2),
    WeatherStation("Lexington", 13.9),
    WeatherStation("Leysin", 6.4),
    WeatherStation("Lézignan-Corbières", 15.2),
    WeatherStation("Lianyungang", 14.5),
    WeatherStation("Libramont", 9.4),
    WeatherStation("Libreville", 25.4),
    WeatherStation("Licence", 12.3),
    WeatherStation("Lichtenstein", 9.1),
    WeatherStation("Lidköping", 7.5),
    WeatherStation("Liège", 10.4),
    WeatherStation("Liesbesch", 15.1),
    WeatherStation("Lieto", 5.3),
    WeatherStation("Lifou", 23.0),
    WeatherStation("Ligonchio", 4.5),
    WeatherStation("Lilongwe", 20.8),
    WeatherStation("Lima", 18.9),
    WeatherStation("Limassol", 19.4),
    WeatherStation("Limbe", 26.5),
    WeatherStation("Limeira", 22.4),
    WeatherStation("Limoux", 13.4),
    WeatherStation("Limpopo", 22.8),
    WeatherStation("Linares", 15.9),
    WeatherStation("Linau", 7.0),
    WeatherStation("Lincoln", 9.6),
    WeatherStation("Lindau", 9.0),
    WeatherStation("Lingen", 9.5),
    WeatherStation("Lingnan", 22.2),
    WeatherStation("Linhe", 10.0),
    WeatherStation("Linköping", 7.4),
    WeatherStation("Linn", 9.0),
    WeatherStation("Linstead", 24.8),
    WeatherStation("Linyuan", 9.0),
    WeatherStation("Lippstadt", 9.3),
    WeatherStation("Lisburn", 9.3),
    WeatherStation("Liscard", 9.7),
    WeatherStation("Lisnarick", 9.3),
    WeatherStation("Lisses", 11.0),
    WeatherStation("Lisses", 11.0),
    WeatherStation("Lissieu", 11.5),
    WeatherStation("Listin", 9.5),
    WeatherStation("Liston", 10.1),
    WeatherStation("Liszt Ferenc", 11.3),
    WeatherStation("Litchfield", 14.6),
    WeatherStation("Litenya", 17.0),
    WeatherStation("Litherland", 9.8),
    WeatherStation("Lithgow", 12.8),
    WeatherStation("Litica", 14.4),
    WeatherStation("Litija", 10.5),
    WeatherStation("Litikhovo", 4.0),
    WeatherStation("Litochoro", 15.7),
    WeatherStation("Litomyšl", 8.0),
    WeatherStation("Litoral", 25.5),
    WeatherStation("Litros", 15.8),
    WeatherStation("Littenheid", 8.8),
    WeatherStation("Littford", 9.7),
    WeatherStation("Littleborough", 9.2),
    WeatherStation("Littlehampton", 10.2),
    WeatherStation("Littleover", 9.6),
    WeatherStation("Littleton", 10.5),
    WeatherStation("Littlewood", 9.8),
    WeatherStation("Lituania", 6.0),
    WeatherStation("Litwak", 8.5),
    WeatherStation("Liu", 17.5),
    WeatherStation("Liuzhou", 19.0),
    WeatherStation("Liverpool", 9.5),
    WeatherStation("Livingston", 8.8),
    WeatherStation("Livingstone", 17.3),
    WeatherStation("Livno", 9.8),
    WeatherStation("Livonia", 8.9),
    WeatherStation("Livorno", 14.1),
    WeatherStation("Livrag", 12.6),
    WeatherStation("Livs", 9.0),
    WeatherStation("Liza", 10.9),
    WeatherStation("Lizhuang", 17.0),
    WeatherStation("Lizhuang", 17.0),
    WeatherStation("Lizhuang", 17.0),
    WeatherStation("Liznjan", 14.6),
    WeatherStation("Ljubljana", 10.9),
    WeatherStation("Ljung", 6.8),
    WeatherStation("Ljungbyholm", 7.2),
    WeatherStation("Ljungby", 7.2),
    WeatherStation("Ljungdahl", 7.5),
    WeatherStation("Ljungesta", 7.5),
    WeatherStation("Ljungheden", 7.4),
    WeatherStation("Ljunghusen", 8.0),
    WeatherStation("Ljungsbyn", 7.6),
    WeatherStation("Ljungskile", 7.6),
    WeatherStation("Ljusdal", 6.0),
    WeatherStation("Ljusne", 6.6),
    WeatherStation("Ljustorp", 7.1),
    WeatherStation("Ljut", 7.4),
    WeatherStation("Lizard", 10.2),
    WeatherStation("Ljaković", 11.1),
    WeatherStation("Ljanica", 9.9),
    WeatherStation("Lješa", 11.0),
    WeatherStation("Ljeto", 10.8),
    WeatherStation("Lješevi", 11.2),
    WeatherStation("Lješivovica", 11.1),
    WeatherStation("Llancaiach", 9.8),
    WeatherStation("Llandaff", 9.8),
    WeatherStation("Llandafydd", 9.7),
    WeatherStation("Llandbedr", 9.8),
    WeatherStation("Llanbedr", 9.8),
    WeatherStation("Llanberis", 8.8),
    WeatherStation("Llanbister", 9.6),
    WeatherStation("Llanblethian", 9.8),
    WeatherStation("Llanbradach", 9.4),
    WeatherStation("Llanbran", 9.6),
    WeatherStation("Llanbrynmair", 9.2),
    WeatherStation("Llancarfan", 9.8),
    WeatherStation("Llancollen", 9.1),
    WeatherStation("Llancowny", 9.7),
    WeatherStation("Llancrug", 8.9),
    WeatherStation("Llandaff North", 9.8),
    WeatherStation("Llandanwg", 9.9),
    WeatherStation("Llandegai", 9.1),
    WeatherStation("Llandegfan", 9.9),
    WeatherStation("Llandegley", 9.3),
    WeatherStation("Llandegwning", 9.8),
    WeatherStation("Llandegwry", 9.8),
    WeatherStation("Llandeloy", 9.8),
    WeatherStation("Llandeilo", 9.7),
    WeatherStation("Llandeilor", 9.7),
    WeatherStation("Llandeloy", 9.8),
    WeatherStation("Llandenny", 9.9),
    WeatherStation("Llanderfel", 9.0),
    WeatherStation("Llanderrfel", 9.0),
    WeatherStation("Llandervel", 9.0),
    WeatherStation("Llandeuliddо", 8.9),
    WeatherStation("Llandevey", 9.8),
    WeatherStation("Llandeven", 9.8),
    WeatherStation("Llandford", 9.6),
    WeatherStation("Llandough", 10.0),
    WeatherStation("Llandow", 9.8),
    WeatherStation("Llandovery", 9.8),
    WeatherStation("Llandow", 9.8),
    WeatherStation("Llandowna", 10.0),
    WeatherStation("Llandre", 9.8),
    WeatherStation("Llandresses", 9.5),
    WeatherStation("Llandridod", 9.2),
    WeatherStation("Llandrillo", 9.0),
    WeatherStation("Llandrindod", 9.2),
    WeatherStation("Llandrindod Wells", 9.2),
    WeatherStation("Llandrinio", 9.4),
    WeatherStation("Llandriscoll", 9.8),
    WeatherStation("Llandrithyd", 9.7),
    WeatherStation("Llandros", 9.8),
    WeatherStation("Llandrwst", 9.0),
    WeatherStation("Llandrygarn", 9.9),
    WeatherStation("Llandrymarch", 9.6),
    WeatherStation("Llandudley", 9.9),
    WeatherStation("Llandudno", 9.9),
    WeatherStation("Llandudno Junction", 9.9),
    WeatherStation("Llandudwen", 9.8),
    WeatherStation("Llanduddо", 9.9),
    WeatherStation("Llandugan", 9.9),
    WeatherStation("Llandugan", 9.9),
    WeatherStation("Llanduganо", 9.9),
    WeatherStation("Llandugunо", 9.9),
    WeatherStation("Llandukо", 9.9),
    WeatherStation("Llandulin", 9.9),
    WeatherStation("Llandulуn", 9.9),
    WeatherStation("Llandulуn", 9.9),
    WeatherStation("Llandulуn", 9.9),
    WeatherStation("Llandullо", 9.9),
    WeatherStation("Llandulо", 9.9),
    WeatherStation("Llandumpо", 10.0),
    WeatherStation("Llandungel", 9.0),
    WeatherStation("Llandungеllay", 9.0),
    WeatherStation("Llandungеllаy", 9.0),
    WeatherStation("Llandung", 9.0),
    WeatherStation("Llandunk", 9.0),
    WeatherStation("Llandunnо", 9.9),
    WeatherStation("Llandunnо", 9.9),
    WeatherStation("Llandunnо", 9.9),
    WeatherStation("Llanduо", 9.9),
    WeatherStation("Llanduptо", 9.9),
    WeatherStation("Llanduptо", 9.9),
    WeatherStation("Llanduрdе", 9.8),
    WeatherStation("Llandurno", 9.9),
    WeatherStation("Llandurrag", 9.9),
    WeatherStation("Llandusant", 9.6),
    WeatherStation("Llandwch", 9.8),
    WeatherStation("Llandwrog", 9.9),
    WeatherStation("Llandwrog", 9.9),
    WeatherStation("Llandwrog", 9.9),
    WeatherStation("Llandwrоg", 9.9),
    WeatherStation("Llandwyv", 9.8),
    WeatherStation("Llandyclai", 10.0),
    WeatherStation("Llandychaiag", 9.9),
    WeatherStation("Llandyде", 9.8),
    WeatherStation("Llandyernog", 9.0),
    WeatherStation("Llandyfaelog", 9.9),
    WeatherStation("Llandyfaeluг", 9.9),
    WeatherStation("Llandyfan", 9.6),
    WeatherStation("Llandyfen", 9.9),
    WeatherStation("Llandyfi", 9.2),
    WeatherStation("Llandyfinog", 9.0),
    WeatherStation("Llandyfrieс", 9.3),
    WeatherStation("Llandygai", 9.1),
    WeatherStation("Llandygarо", 9.8),
    WeatherStation("Llandygetaiг", 9.8),
    WeatherStation("Llandygodо", 9.8),
    WeatherStation("Llandygнаeо", 9.9),
    WeatherStation("Llandygνidо", 9.8),
    WeatherStation("Llandygніl", 9.9),
    WeatherStation("Llandygніо", 9.9),
    WeatherStation("Llandygnіа", 9.9),
    WeatherStation("Llandygnіm", 9.2),
    WeatherStation("Llandygnіmіll", 9.2),
    WeatherStation("Llandygnіsоrt", 10.0),
    WeatherStation("Llandуguаll", 9.0),
    WeatherStation("Llandугаn", 10.0),
    WeatherStation("Llandugаnаeоr", 10.0),
    WeatherStation("Llandугаn", 10.0),
    WeatherStation("Llandугаw", 9.6),
    WeatherStation("Llandугіnn", 8.8),
    WeatherStation("Llandугіnn", 8.8),
    WeatherStation("Llandуго", 10.0),
    WeatherStation("Llandугоеn", 10.0),
    WeatherStation("Llandугоеn", 10.0),
    WeatherStation("Llandугоg", 9.8),
    WeatherStation("Llandугохоеl", 9.9),
    WeatherStation("Llandугохоmеi", 9.9),
    WeatherStation("Llandугохоmеiеn", 9.9),
    WeatherStation("Llandугохоmо", 9.9),
    WeatherStation("Llandугохоmоеl", 9.9),
    WeatherStation("Llandугохоm", 9.9),
    WeatherStation("Llandугохonnе", 9.9),
    WeatherStation("Llandугохор", 9.9),
    WeatherStation("Llandугохоrо", 9.9),
    WeatherStation("Llandугохоuм", 9.9),
    WeatherStation("Llandughuir", 9.9),
    WeatherStation("Llandugai", 9.1),
    WeatherStation("Llandугаi", 9.1),
    WeatherStation("Llandугаil", 9.1),
    WeatherStation("Llandугаilаi", 9.1),
    WeatherStation("Llandugair", 9.1),
    WeatherStation("Llandugughai", 9.1),
    WeatherStation("Llandughаm", 9.9),
    WeatherStation("Llandughan", 9.9),
    WeatherStation("Llandughар", 9.9),
    WeatherStation("Llandughill", 9.3),
    WeatherStation("Llandugill", 9.3),
    WeatherStation("Llandughоrn", 9.4),
    WeatherStation("Llandugо", 10.0),
    WeatherStation("Llandughrun", 9.9),
    WeatherStation("Llandуго", 10.0),
    WeatherStation("Llandugh", 9.9),
    WeatherStation("Llandugуl", 9.9),
    WeatherStation("Llandugуm", 9.1),
    WeatherStation("Llandugуm", 9.1),
    WeatherStation("Llandugуmоеl", 9.1),
    WeatherStation("Llandugуmеiеn", 9.1),
    WeatherStation("Llandugуmеi", 9.1),
    WeatherStation("Llandughаll", 9.3),
    WeatherStation("Llandугоn", 10.0),
    WeatherStation("Llandugоnn", 10.0),
    WeatherStation("Llandugоnn", 10.0),
    WeatherStation("Llandugоnn", 10.0),
    WeatherStation("Llandугыg", 9.9),
    WeatherStation("Llandугуg", 9.9),
    WeatherStation("Nashville", 15.4),
    WeatherStation("Nassau", 24.6),
    WeatherStation("Ndola", 20.3),
    WeatherStation("New Delhi", 25.0),
    WeatherStation("New Orleans", 20.7),
    WeatherStation("New York City", 12.9),
    WeatherStation("Ngaoundéré", 22.0),
    WeatherStation("Niamey", 29.3),
    WeatherStation("Nicosia", 19.7),
    WeatherStation("Niigata", 13.9),
    WeatherStation("Nouadhibou", 21.3),
    WeatherStation("Nouakchott", 25.7),
    WeatherStation("Novosibirsk", 1.7),
    WeatherStation("Nuuk", -1.4),
    WeatherStation("Odesa", 10.7),
    WeatherStation("Odienné", 26.0),
    WeatherStation("Oklahoma City", 15.9),
    WeatherStation("Omaha", 10.6),
    WeatherStation("Oranjestad", 28.1),
    WeatherStation("Oslo", 5.7),
    WeatherStation("Ottawa", 6.6),
    WeatherStation("Ouagadougou", 28.3),
    WeatherStation("Ouahigouya", 28.6),
    WeatherStation("Ouarzazate", 18.9),
    WeatherStation("Oulu", 2.7),
    WeatherStation("Palembang", 27.3),
    WeatherStation("Palermo", 18.5),
    WeatherStation("Palm Springs", 24.5),
    WeatherStation("Palmerston North", 13.2),
    WeatherStation("Panama City", 28.0),
    WeatherStation("Parakou", 26.8),
    WeatherStation("Paris", 12.3),
    WeatherStation("Perth", 18.7),
    WeatherStation("Petropavlovsk-Kamchatsky", 1.9),
    WeatherStation("Philadelphia", 13.2),
    WeatherStation("Phnom Penh", 28.3),
    WeatherStation("Phoenix", 23.9),
    WeatherStation("Pittsburgh", 10.8),
    WeatherStation("Podgorica", 15.3),
    WeatherStation("Pointe-Noire", 26.1),
    WeatherStation("Pontianak", 27.7),
    WeatherStation("Port Moresby", 26.9),
    WeatherStation("Port Sudan", 28.4),
    WeatherStation("Port Vila", 24.3),
    WeatherStation("Port-Gentil", 26.0),
    WeatherStation("Portland (OR)", 12.4),
    WeatherStation("Porto", 15.7),
    WeatherStation("Prague", 8.4),
    WeatherStation("Praia", 24.4),
    WeatherStation("Pretoria", 18.2),
    WeatherStation("Pyongyang", 10.8),
    WeatherStation("Rabat", 17.2),
    WeatherStation("Rangpur", 24.4),
    WeatherStation("Reggane", 28.3),
    WeatherStation("Reykjavík", 4.3),
    WeatherStation("Riga", 6.2),
    WeatherStation("Riyadh", 26.0),
    WeatherStation("Rome", 15.2),
    WeatherStation("Roseau", 26.2),
    WeatherStation("Rostov-on-Don", 9.9),
    WeatherStation("Sacramento", 16.3),
    WeatherStation("Saint Petersburg", 5.8),
    WeatherStation("Saint-Pierre", 5.7),
    WeatherStation("Salt Lake City", 11.6),
    WeatherStation("San Antonio", 20.8),
    WeatherStation("San Diego", 17.8),
    WeatherStation("San Francisco", 14.6),
    WeatherStation("San Jose", 16.4),
    WeatherStation("San José", 22.6),
    WeatherStation("San Juan", 27.2),
    WeatherStation("San Salvador", 23.1),
    WeatherStation("Sana'a", 20.0),
    WeatherStation("Santo Domingo", 25.9),
    WeatherStation("Sapporo", 8.9),
    WeatherStation("Sarajevo", 10.1),
    WeatherStation("Saskatoon", 3.3),
    WeatherStation("Seattle", 11.3),
    WeatherStation("Ségou", 28.0),
    WeatherStation("Seoul", 12.5),
    WeatherStation("Seville", 19.2),
    WeatherStation("Shanghai", 16.7),
    WeatherStation("Singapore", 27.0),
    WeatherStation("Skopje", 12.4),
    WeatherStation("Sochi", 14.2),
    WeatherStation("Sofia", 10.6),
    WeatherStation("Sokoto", 28.0),
    WeatherStation("Split", 16.1),
    WeatherStation("St. John's", 5.0),
    WeatherStation("St. Louis", 13.9),
    WeatherStation("Stockholm", 6.6),
    WeatherStation("Surabaya", 27.1),
    WeatherStation("Suva", 25.6),
    WeatherStation("Suwałki", 7.2),
    WeatherStation("Sydney", 17.7),
    WeatherStation("Tabora", 23.0),
    WeatherStation("Tabriz", 12.6),
    WeatherStation("Taipei", 23.0),
    WeatherStation("Tallinn", 6.4),
    WeatherStation("Tamale", 27.9),
    WeatherStation("Tamanrasset", 21.7),
    WeatherStation("Tampa", 22.9),
    WeatherStation("Tashkent", 14.8),
    WeatherStation("Tauranga", 14.8),
    WeatherStation("Tbilisi", 12.9),
    WeatherStation("Tegucigalpa", 21.7),
    WeatherStation("Tehran", 17.0),
    WeatherStation("Tel Aviv", 20.0),
    WeatherStation("Thessaloniki", 16.0),
    WeatherStation("Thiès", 24.0),
    WeatherStation("Tijuana", 17.8),
    WeatherStation("Timbuktu", 28.0),
    WeatherStation("Tirana", 15.2),
    WeatherStation("Toamasina", 23.4),
    WeatherStation("Tokyo", 15.4),
    WeatherStation("Toliara", 24.1),
    WeatherStation("Toluca", 12.4),
    WeatherStation("Toronto", 9.4),
    WeatherStation("Tripoli", 20.0),
    WeatherStation("Tromsø", 2.9),
    WeatherStation("Tucson", 20.9),
    WeatherStation("Tunis", 18.4),
    WeatherStation("Ulaanbaatar", -0.4),
    WeatherStation("Upington", 20.4),
    WeatherStation("Ürümqi", 7.4),
    WeatherStation("Vaduz", 10.1),
    WeatherStation("Valencia", 18.3),
    WeatherStation("Valletta", 18.8),
    WeatherStation("Vancouver", 10.4),
    WeatherStation("Veracruz", 25.4),
    WeatherStation("Vienna", 10.4),
    WeatherStation("Vientiane", 25.9),
    WeatherStation("Villahermosa", 27.1),
    WeatherStation("Vilnius", 6.0),
    WeatherStation("Virginia Beach", 15.8),
    WeatherStation("Vladivostok", 4.9),
    WeatherStation("Warsaw", 8.5),
    WeatherStation("Washington, D.C.", 14.6),
    WeatherStation("Wau", 27.8),
    WeatherStation("Wellington", 12.9),
    WeatherStation("Whitehorse", -0.1),
    WeatherStation("Wichita", 13.9),
    WeatherStation("Willemstad", 28.0),
    WeatherStation("Winnipeg", 3.0),
    WeatherStation("Wrocław", 9.6),
    WeatherStation("Xi'an", 14.1),
    WeatherStation("Yakutsk", -8.8),
    WeatherStation("Yangon", 27.5),
    WeatherStation("Yaoundé", 23.8),
    WeatherStation("Yellowknife", -4.3),
    WeatherStation("Yerevan", 12.4),
    WeatherStation("Yinchuan", 9.0),
    WeatherStation("Zagreb", 10.7),
    WeatherStation("Zanzibar City", 26.0),
    WeatherStation("Zürich", 9.3),
]


def main():
    if len(sys.argv) != 2:
        print("Usage: python generator.py <number of records to create>", file=sys.stderr)
        sys.exit(1)
    
    try:
        size = int(sys.argv[1])
    except ValueError:
        print("Invalid value for <number of records to create>", file=sys.stderr)
        print("Usage: python generator.py <number of records to create>", file=sys.stderr)
        sys.exit(1)
    
    start_time = time.time()
    checkpoint = size // 10  # 10% 단위
    
    with open(MEASUREMENT_FILE, 'w', encoding='utf-8') as sw:
        for i in range(size):
            if i > 0 and i % checkpoint == 0:
                progress_percent = (i / size) * 100
                elapsed_ms = (time.time() - start_time) * 1000
                print(f"[{progress_percent:.0f}%] Wrote {i:,} measurements in {elapsed_ms:,.3f} ms")
            
            weather_station = random.choice(stations)
            sw.write(str(weather_station) + '\n')
    
    elapsed_ms = (time.time() - start_time) * 1000
    print(f"[100%] Created file with {size:,} measurements in {elapsed_ms:,.3f} ms")


if __name__ == "__main__":
    main()